export default {
  videoItems: [
    {
      name: "youtube",
      icon: "fab fa-youtube",
      account: "tide FM",
      number: "15",
      videoId: "GqXnyg7yYOQ",
    },
    {
      name: "youtube",
      icon: "fab fa-youtube",
      account: "tide FM",
      number: "14",
      videoId: "564Qw0LfL5w",
    },
    {
      name: "youtube",
      icon: "fab fa-youtube",
      account: "tide FM",
      number: "13",
      videoId: "x7xegEN0TMo",
    },
    {
      name: "youtube",
      icon: "fab fa-youtube",
      account: "tide FM",
      number: "12",
      videoId: "vIq7EGCAiDI",
    },
    {
      name: "youtube",
      icon: "fab fa-youtube",
      account: "tide FM",
      number: "11",
      videoId: "RMZfCYkjSi4",
    },
    {
      name: "youtube",
      icon: "fab fa-youtube",
      account: "tide FM",
      number: "10",
      videoId: "qi6Utttn_hc",
    },
    {
      name: "youtube",
      icon: "fab fa-youtube",
      account: "tide FM",
      number: "9",
      videoId: "HhW1VnjBpPE",
    },
    {
      name: "youtube",
      icon: "fab fa-youtube",
      account: "tide FM",
      number: "8",
      videoId: "G_IhID1TDIk",
    },
    {
      name: "youtube",
      icon: "fab fa-youtube",
      account: "tide FM",
      number: "7",
      videoId: "ArMqeYKxUAM",
    },
    {
      name: "youtube",
      icon: "fab fa-youtube",
      account: "tide FM",
      number: "6",
      videoId: "aZYSKCFkLmM",
    },
    {
      name: "youtube",
      icon: "fab fa-youtube",
      account: "tide FM",
      number: "5",
      videoId: "iQWJeh2iGcg",
    },
    {
      name: "youtube",
      icon: "fab fa-youtube",
      account: "tide FM",
      number: "4",
      videoId: "xdoYySi8e-0",
    },
    {
      name: "youtube",
      icon: "fab fa-youtube",
      account: "tide FM",
      number: "3",
      videoId: "JyNuZMLspCA",
    },
    {
      name: "youtube",
      icon: "fab fa-youtube",
      account: "tide FM",
      number: "2",
      videoId: "19jHxM73LC0",
    },
    {
      name: "youtube",
      icon: "fab fa-youtube",
      account: "tide FM",
      number: "1",
      videoId: "SqwV8AraR94",
    },
  ],
  radioItems: [
    {
      name: "spotify",
      icon: "fab fa-spotify",
      account: "Ritika FM",
      number: "1",
      radioId: "7zOkCwJavRIHSUmQwJXlcC",
    },
    {
      name: "spotify",
      icon: "fab fa-spotify",
      account: "でふらじお",
      number: "40",
      radioId: "0vq0bNUyIv1PgAlx4lYU6I",
    },
  ],
};
